### ISSUE TITLE
Available Quizzes Page Design "Bug"

### ISSUE THREAD

**Issue by cMikolai** [chingu-voyages/moonshot-chingu-quiz#122]
In the moment, when there are only two results available, there is a lot of space in between these two quiz tiles on the "Quiz Page".
It would look more consistent to have the tiles close together as if there would be three in the row, so to say.

Example as it is right now:

![Bildschirmfoto 2020-10-31 um 15 55 06](https://user-images.githubusercontent.com/29103440/97782425-bcff7c00-1b91-11eb-9862-32ca35f530cf.png)

Expected to be more consistent like this: 

![Bildschirmfoto 2020-10-31 um 15 55 13](https://user-images.githubusercontent.com/29103440/97782422-bbce4f00-1b91-11eb-99cc-80351548d622.png)

![Bildschirmfoto 2020-10-31 um 15 58 42](https://user-images.githubusercontent.com/29103440/97782468-f7691900-1b91-11eb-8690-5ea444b05603.png)

**Comment by Soreg** [comment]
@cMikolai I'm grabbing this even though it's labeled as "good first issue". Nobody took it yet, and it's triggering my OCD 😅
