### ISSUE TITLE
The About page does not showcase the people who made this beautiful app a reality

### ISSUE THREAD

**Issue by tropicalchancer** [chingu-voyages/moonshot-chingu-quiz#146]
**Is your feature request related to a problem? Please describe.**
[**Live footage of me going to the About page and not seeing all ya'll on there in some way**](https://giphy.com/gifs/bbc-bbc-two-versailles-2-51Y804o23LzorasImh)

**Describe the solution you'd like**
10x the recognition

**Describe alternatives you've considered**
Dusting off the old typewriter...

**Additional context**
If people are comfortable with it, it would be cool to have some way to showcase everyone who has contributed to it on here and whenever someone new contributes they are added as well. 

p.s. LOVE THE APP! 
p.s.s. LOVE THE LINE "We believe in Freedom and Independence"

**Story:**
As a user I would like to know who built this app so that I can stalk them to see what else they may be working on.

**Details:**
- Use GH API to get info about contributors to this project dynamically
- Add contributors Avatar and link to their profile on the About page

**Comment by Soreg** [comment]
@tropicalchancer Thanks for creating this. We'll be discussing this issue in the Core Team in the near future :)

**Comment by Soreg** [comment]
Assigning this to myself as nobody grabbed it yet :)
