### ISSUE TITLE
Quiz Page: Random Question Order

### ISSUE THREAD

**Issue by ghost** [chingu-voyages/moonshot-chingu-quiz#148]
**Is your feature request related to a problem? Please describe.**
Quiz quesitons currently appear in the same order everytime the quiz is taken.

**Describe the solution you'd like**
Random the order the questions are presented and perhaps the answers as well.

**Comment by xarrijorge** [comment]
Working on this already @silentkdev?

**Comment by ghost** [comment]
Not yet we are finalizing some issues that we want to add for the next release.  I believe we will have the issues ready to be picked up on wednesday.  But if you are interested I will reach out to you first regarding this specific issue if you like @xarrijorge

**Comment by jaytula** [comment]
I created a pull request #150 for this issue. First time contributing to this project... let me know if I'm not doing things right. 😅

**Comment by jaytula** [comment]
no rush or anything 😃  but in case it has gone unnoticed... pull request #150 was updated to shuffle answer orders.

**Comment by jaytula** [comment]
I believe this issue can be closed. Commit 0957a5b has been merged into the *dev* branch.
