### ISSUE TITLE
[Authentication] User Profile

### ISSUE THREAD

**Issue by cMikolai** [chingu-voyages/moonshot-chingu-quiz#164]
As a user, I would like to have a profile page so that I am able to visually check my progress.

**Comment by jaytula** [comment]
FYI, Additional commits were added to pull request #169 that implement a *User Page* listing quiz results that the user has taken.

This can be tested here: https://moonshot-chingu-quiz.vercel.app/ 

- Login
- Take a test and submit
- Click the Profile link in the upper right hand corner

![image](https://user-images.githubusercontent.com/75389/125540426-84dc5379-2ab0-4dc7-bb86-1ffcbf59e6a6.png)

**Comment by jaytula** [comment]
I've improved the styling of the quiz results in commit 0a6649e

![image](https://user-images.githubusercontent.com/75389/127782811-cb48adf3-0ce5-4e1a-940d-2a40471aa48e.png)
