### ISSUE TITLE
Complete URL used in Readme

### ISSUE THREAD

**Issue by Guneetsinghtuli** [chingu-voyages/moonshot-chingu-quiz#174]
## Problem
An entire URL is being used in the Readme file which can be managed in a better way that can make the readme file more readable.

## Better way
[Figma](https://www.figma.com/file/2mKq8rdawiJO6EEVwugWYp/Chingu_Mockups?node-id=84%3A198)
or
[www.figma.com](https://www.figma.com/file/2mKq8rdawiJO6EEVwugWYp/Chingu_Mockups?node-id=84%3A198)

I would like to take up this issue and solve it if you think that solving this issue can improve the documentation.

## Screenshot 
![Screenshot 2021-09-20 at 6 40 32 PM](https://user-images.githubusercontent.com/48324492/134008518-ed2de1c3-3cad-4ff3-b6d7-f15a1a819ab6.png)

**Comment by jaytula** [comment]
@Guneetsinghtuli Sure go for it. 🚀

**Comment by Guneetsinghtuli** [comment]
@jaytula I have made a pull request please have a look and if any changes are required please let me know.
