### ISSUE TITLE
Make decision on whether we want a permissions table or if a roles table is enough

### ISSUE THREAD

**Issue by jaytula** [chingu-voyages/moonshot-chingu-quiz#182]
We can either decide that a `roles` table is sufficient or to also have a `permissions` table.  

If there is a `permissions` table, then we would assign permissions to roles. And we would assign role(s) to users.

Where we'd like to limit access, we would test whether a user has a permission versus checking whether they have a role.

If a decision is made in favor, a new issue should be created for the creation of the permissions table.

**Comment by ZumDeWald** [comment]
This should be a Core Team discussion point and not an issue until we have made a decision.
