### ISSUE TITLE
Implement `GET /api/admin/roles` endpoint

### ISSUE THREAD

**Issue by jaytula** [chingu-voyages/moonshot-chingu-quiz#189]
This requires that #188 be completed first.

We need an endpoint added in Next for returning roles from the roles table. It would be with the apis in `admin/roles` folder and `get.ts` file.
That structure will give us the desired endpoint `/api/admin/roles/get`.

The endpoint should use the function from #188 to get and return a list of roles.

**Comment by amirfakhrullah** [comment]
Hi, I saw that the issue #188 already closed and no one proceeded with this issue yet. I'm interested in fixing this. Can you assign me this issue?
