### ISSUE TITLE
Quiz Page: Timing

### ISSUE THREAD

**Issue by gius88** [chingu-voyages/moonshot-chingu-quiz#22]
**Story:** 
As a user I would like a timer that counts up during the quiz so that I can track my time and use it as a gauge for progress in my development.

**Details:**
- Timer added to quiz
- Timer starts counting up as soon as the first question is loaded
- User can 'show / hide' timer during the quiz
- Timer stops when last answer is submitted
- Time to complete is shown on results page along with overall score

**Comment by ZumDeWald** [comment]
**Note**: Please be sure to make any PR for this issue to the `feature/quiz-page` branch and not Dev as this ties into a larger feature, thanks!
