### ISSUE TITLE
Quiz Page: Submit Button

### ISSUE THREAD

**Issue by gius88** [chingu-voyages/moonshot-chingu-quiz#23]
As a User once I have selected my answer I click on Submit button so that I can continue with my test to the next question.

Tasks:
- Build buttons to be used throughout the quiz

Dependant on #21

**Comment by cMikolai** [comment]
I'd like to add a little clarification to prevent confusion:

- There should be a next button throughout the questions for a single quiz.
- At the end of the quiz I want to be able to "submit" it, so the last question should have a submit button

- Open for discussion: not only next but also previous buttons

**Comment by super-ming** [comment]
I can take this one.
