### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by gius88** [chingu-voyages/moonshot-chingu-quiz#27]
As a User I can see who has built the website with photos and names.

**Comment by superneutrino8** [comment]
@Soreg Can I try this one? I know this is only for CORE-TEAM

**Comment by Soreg** [comment]
@superneutrino8 Sure, go ahead :) 
I set up 2 "sub-issues" which should cover the rest of this "About us" page - #83 and #84.

Please follow the guidelines for branching, and branch out from "feature/#27-About-Us-Page"

The design can be found here: https://www.figma.com/file/2mKq8rdawiJO6EEVwugWYp/Chingu_Mockups?node-id=84%3A198 - under the "MAIN THEME" page 🙂 

Please reach out again if you have any questions!

**Comment by Soreg** [comment]
* Set status to "Ready for Review / QA", as the branch is not in develop.
@cMikolai did design want to test it locally before merging into dev?
