### ISSUE TITLE
Dark Mode / Light Mode

### ISSUE THREAD

**Issue by gius88** [chingu-voyages/moonshot-chingu-quiz#29]
As a user I would be able to switch between light/dark mode to choose which contrast helps me focus on the content.

**Comment by ZumDeWald** [comment]
**Note:** We are using a Theme Provider for all of our colors throughout the app. If you are interested in this ticket be sure to honor the system in place and reach out with questions.

**Comment by Soreg** [comment]
**Note 2 - important:** Right now, we have colors named "darkGreen" etc., which might not be dark-green on the new theme.
We should probably come up with (and rename) theme-colors once we add the second theme, so the naming fit multiple themes. Maybe we should even split the colors out into some shared components / objects inside the theme objects (ex. "shared", "header", "quiz" etc.)

**Comment by dpajek** [comment]
The current mockups have both white and dark sections in the same page (eg, the "have fun" "grow yourself" section on the landing page). What color do you want to use for this section in the dark vs light theme?

**Comment by dpajek** [comment]
Let me know what you think of the approach in the PR above. Happy to change....

I left the explicit colour names (e.g., darkGreen) since there may be some layouts/pages that will have the same colour on each theme. I added a few new variables that change depending on the theme.
```
const darkTheme = {
  colors: {
    light: "#fff",
    dark: "#000",
    grey: "#333",
    ...
    backgroundPrimary: "#333",
    backgroundMenu: "#333",
    textPrimary: "#fff",
    textMenu: "#fff",
    greenPrimary: "#18e28c",
  },
};

const lightTheme = {
  colors: {
    light: "#fff",
    dark: "#000",
    ...
    backgroundPrimary: "#EBEFF3",
    backgroundMenu: "#fff",
    textPrimary: "#333",
    textMenu: "#057a55",
    greenPrimary: "#057a55",
  },
};
```
