### ISSUE TITLE
Quiz Page: Pre-Quiz Message

### ISSUE THREAD

**Issue by gius88** [chingu-voyages/moonshot-chingu-quiz#34]
As a user it would be helpful to have something letting me know the quiz is being prepared.

**Comment by ZumDeWald** [comment]
**Note:** This feature requires that the Quiz Page be in place.

We envision this as a short message that appears before the quiz starts. It will be a chance for the user to control when the quiz / timer begins. See the design here: https://www.figma.com/file/2mKq8rdawiJO6EEVwugWYp/Chingu_Mockups?node-id=84%3A1157.
