### ISSUE TITLE
Add PUT route to api quiz end point.

### ISSUE THREAD

**Issue by silentkdev** [chingu-voyages/moonshot-chingu-quiz#57]
The api end point /api/v1/quiz needs a PUT route added to the router with associated router handler. 

Route should accept a quiz object and replace the quiz data in database with the matching id.

Quiz data in database is separated into three tables: quiz, question, answer.  Each row relating to the quiz data for each table will need to be adjusted based on the quiz object properties send to the PUT route.

![Untitled](https://user-images.githubusercontent.com/60763269/95001598-449c9f80-0580-11eb-8b15-185bbc311301.png)

**Comment by rmcguire6** [comment]
Actually PR #93 has changed the schema. Please refer to that updated schema

**Comment by dpajek** [comment]
Doesn't this put route exist already? Or are you envisioning something different from what already exists?

**Comment by silentkdev** [comment]
@dpajek PUT route does not exist current.  POST route may be what you are thinking of.  We'll use the POST to create new quiz whereas PUT will be to update existing quizzes.  The schema has changed so the image above is outdated.  If you're wanting to take this issue on I can write up another plan like I did on the random quiz end point and assign this to you.

**Comment by dpajek** [comment]
Ahh. Now i know those are different things 🙈

That would be great. I’d like to do it. Thanks!

**Comment by silentkdev** [comment]
@dpajek sorry it took so long to get the ball rolling on this one.  Looks like we are finally ready to go.

![Untitled](https://user-images.githubusercontent.com/60763269/97039742-bfbef900-1521-11eb-8646-b998cb40b2bf.png)

This is the current schema above.

We need an end point for `/api/v1/quiz/:id` that accepts a PUT request.  The body of this request should consist of all the columns for the quiz table listed above.  You'll want to mount the route with `router.put(/:id, routeController)`in `/server/routes/apiV1/quiz.js`.  The controller should go in `/server/controllers/apiV1/quiz/putById.js` and lastly any queries to the database you write while making this end point should go into `/server/db/queries/quiz/update.js`.

Let me know if you have any questions, or run into any issues.
