### ISSUE TITLE
Frontpage "What is Chingu" section

### ISSUE THREAD

**Issue by Soreg** [chingu-voyages/moonshot-chingu-quiz#65]
https://www.figma.com/file/2mKq8rdawiJO6EEVwugWYp/Chingu_Mockups?node-id=84%3A198
We need to implement the "What is Chingu" section, including an image, title, text and buttons

**Comment by superneutrino8** [comment]
Hey @cMikolai, Can I give this a try?

**Comment by cMikolai** [comment]
@superneutrino8 Hey there, Yeah, you can go for it, cool! 👍🏻 I'l assign you
