### ISSUE TITLE
Contribute page

### ISSUE THREAD

**Issue by Soreg** [chingu-voyages/moonshot-chingu-quiz#66]
We need a basic "Contribute" page, with basic information about how to contribute, and relevant links to ex. Github

**Comment by lily-law** [comment]
I'm going to have a go with this one today

**Comment by cMikolai** [comment]
@lily-law Amazing - let us know if you need anything. I think there are no specific designs for this as for now :)

**Comment by lily-law** [comment]
@cMikolai Thanks, I've sketched up something to start with https://www.figma.com/file/nei895Fh29EUqK9bo8JOFa/Untitled?node-id=0%3A1 If it looks OK I'll have a look at implementing this later.

**Comment by ZumDeWald** [comment]
That looks great @lily-law ! The one to the right, with the grey background looks more inline with what we're going for, trying to use the green more sparingly for call to action and such. Thanks for picking this up. Let us know if you have questions.

**Comment by lily-law** [comment]
@ZumDeWald Thanks, OK cool, that makes sense with the green. I'll code this now and PR

**Comment by lily-law** [comment]
So font styling, should I add this to my styled components or are things like font size going to added later globally?

**Comment by Soreg** [comment]
@lily-law Great to see you joining. Welcome! :) 
Regarding fonts and buttons, then they will be implemented in this PR: https://github.com/chingu-voyages/moonshot-chingu-quiz/pull/56.
The plan is to have some shared text / button-elements, which can be imported (and extended) in different files.

We _might_ end up adding a separate Button-component later - though this is still being discussed :) 

For now, feel free to just add font-sizes, line-heights and buttons as needed in the files you're making. We'll probably add an issue later to clean up remaining files :)

**Comment by lily-law** [comment]
@Soreg Thanks, Okay cool that makes things simpler for now
